default: &default
  adapter: mysql2
  host: localhost
  port: 3036
  username: root
  password: alpen101
  encoding: utf8

development:
  <<: *default
  database: genshin-build_development

test:
  <<: *default
  database: genshin-build_test